### ISSUE TITLE
Arduino build error

### ISSUE THREAD

**Issue by umeshwalkar** [Wiz-IO/Arduino-Quectel-M66#2]
Hi,
I am unable to compile. i have followed steps to install Arduino-Quectel-M66.
following error received.

"C:\\Users\\Umesh\\AppData\\Local\\Arduino15\\packages\\WizIO\\tools\\m66_tools\\1.0/GFH_Generator.exe" "C:\\Users\\Umesh\\AppData\\Local\\Temp\\arduino_build_438519/ARDUINO.bin"
**cannot open the file C:\Program Files (x86)\Arduino\temp.bin!**

Using library Ethernet at version 1.0.0 in folder: C:\Users\Umesh\AppData\Local\Arduino15\packages\WizIO\hardware\m66\2.0.0\libraries\Ethernet 
exit status -1
Error compiling for board Quectel M66 Module

So, I assigned admin right to 'GFH_Generator.exe" in "C:\Users\Umesh\AppData\Local\Arduino15\packages\WizIO\tools\m66_tools\1.0" folder.

then I receiving following error.

"C:\\Users\\Umesh\\AppData\\Local\\Arduino15\\packages\\WizIO\\tools\\m66_gcc\\1.70201.0\\bin\\arm-none-eabi-objcopy" -O binary "C:\\Users\\Umesh\\AppData\\Local\\Temp\\arduino_build_438519/tcp_http.ino.dat" "C:\\Users\\Umesh\\AppData\\Local\\Temp\\arduino_build_438519/ARDUINO.bin"
"C:\\Users\\Umesh\\AppData\\Local\\Arduino15\\packages\\WizIO\\tools\\m66_tools\\1.0/GFH_Generator.exe" "C:\\Users\\Umesh\\AppData\\Local\\Temp\\arduino_build_438519/ARDUINO.bin"
Using library Ethernet at version 1.0.0 in folder: C:\Users\Umesh\AppData\Local\Arduino15\packages\WizIO\hardware\m66\2.0.0\libraries\Ethernet 
**fork/exec C:\Users\Umesh\AppData\Local\Arduino15\packages\WizIO\tools\m66_tools\1.0/GFH_Generator.exe: The requested operation requires elevation.
Error compiling for board Quectel M66 Module.**

Windows 10, 64 bit.
Arduino IDE 1.8.9

**Comment by Wiz-IO** [comment]
Hi
Arduino & Admin rights

**Comment by umeshwalkar** [comment]
Thanks,

running Arduino as administrator compiles program.
received **[ UPLOAD ] USE QFlash Tool**
so, for programming i used QFlash.exe and files from "C:\Users\Umesh\AppData\Local\Temp\arduino_build_695874" 
Is this right procedure??

**Comment by Wiz-IO** [comment]
yes, get bin & ini from project build folder

**Comment by umeshwalkar** [comment]
able to program.
thanks.

I have one more query regarding **platform-quectel**
I am using **arduino framework** using platform-io.
able to compile code but uploading is terminated in 3rd step.

<<<<<<<<<<<< QUECTEL M66 MODULE 2018 Georgi Angelov >>>>>>>>>>>>
CONFIGURATION: https://docs.platformio.org/page/boards/quectel/m66.html
PLATFORM: Quectel 2.1.01 #1b8c472 > Quectel M66 module
HARDWARE: ARM, MT6261 260MHz, 100KB RAM, 360KB Flash
DEBUG: Current (uart) On-board (uart)
PACKAGES:
 - framework-quectel c17af04
 - tool-quectel b65e42d
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 6 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
ADD HEADER
Checking size .pio\build\m66\program.elf
BIN SIZE: 21.625 kB
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]   9.1% (used 9332 bytes from 102400 bytes)
Flash: [          ]   0.1% (used 208 bytes from 368640 bytes)
Configuring upload protocol...
Looking for upload port...
Use manually specified: COM4
Uploading: program
<.........................> DONE
Initialising
<.......     ...................................................................................> DONE
Sending MTK Download Agent. Please wait
<..................................................................................................................> DONE

*** [upload] Explicit exit, status 2
ERROR: APP: MMM

Please guide on this. working through platformio is more convenient for me.

**Comment by Wiz-IO** [comment]
you can use QFlash tool 
I have any bugs in python uploader ( MC60 / M66 )

**Comment by umeshwalkar** [comment]
ok. using QFlash tool it works.
